Дата и время вызова функции: 27 Oct 2021, 22:12:45
Имя функции: get_foo
Аргументы:  (5, 25) {'c': 12, 'd': 100} 
Возвращаемое значение: 1230
Путь к логам: F:\Courses\Netology\Python_pro\home_05\file\log.txt
------------------------
